[package]
name = "aserial"
version = "0.1.0"
authors = ["Kamil Koczurek <koczurekk@gmail.com>"]
edition = "2018"

[dependencies]
cpal = "0.10.0"
rodio = "0.10.0"
rustfft = "3.0.1"
minifb = "0.13.0"
plotters = { version = "^0.2.12", features = ["bitmap"] }
